### ISSUE TITLE
Bug: 无法识别到 Edge

### ISSUE THREAD

**Issue by H4M5TER** [koishijs/koishi-plugin-puppeteer#10]
版本 3.3.0 和 3.3.3 可复现

![F@~3@C LJRD$@WBF V U`IY](https://user-images.githubusercontent.com/21092951/213279299-e6638ae5-e1db-428c-9426-79c7c75dd857.jpg)
![C)2(3R7PLH3T_L$%4911I9](https://user-images.githubusercontent.com/21092951/213279205-aaf8bdd6-c59d-4685-a187-a39ed8b50918.jpg)

**Comment by ilharp** [comment]
经开发群群友测试，该问题为某人实现功能后未发版所致。发版后即可解决。

某人出来说话 @shigma

**Comment by shigma** [comment]
喵

**Comment by shigma** [comment]
已修复。
