### ISSUE TITLE
Feature(pptr): 让 Puppeteer 尊重 Koishi 全局代理设置

### ISSUE THREAD

**Issue by Lipraty** [koishijs/koishi-plugin-puppeteer#22]
目前 pptr 是没有跟随 Koishi 全局代理的设置：
https://github.com/koishijs/koishi-plugin-puppeteer/blob/a93fcda92c82c8ab0fbc6b1f8c297ee237dc5179/packages/core/src/index.ts#L58-L61

希望尊重 Koishi 全局代理设置（

想的一个笨笨方法：

``` TypeScript
//add proxyAgent
if(ctx.root.config.request.proxyAgent){
   this.config.args.push([`--proxy-server=${ctx.root.config.request.proxyAgent}`])
}
this.browser = await puppeteer.launch({ 
   ...this.config, 
   executablePath, 
 }) 
```

**Comment by MaikoTan** [comment]
A possible way to specify the global proxy for Chrome was by environment variables, but I am not very sure if that is implementable with puppeteer.

**Comment by H4M5TER** [comment]
这个做法应该就是最好的

https://github.com/puppeteer/puppeteer/blob/main/examples/proxy.js

https://www.chromium.org/developers/design-documents/network-settings/

**Comment by Lipraty** [comment]
> 这个做法应该就是最好的

所以目前来说添加启动选项是比较好的实践吗，梦梦怎么看

**Comment by shigma** [comment]
这个 proxy-server 支持 socks 吗？

**Comment by Lipraty** [comment]
> 这个 proxy-server 支持 socks 吗？

看了下，支持的：

> To configure chrome to proxy traffic through the SOCKS v5 proxy server myproxy:8080, launch chrome with these two command-line flags:
> 
> --proxy-server="socks5://myproxy:8080"
> 
> --host-resolver-rules="MAP * ~NOTFOUND , EXCLUDE myproxy"

详见：https://www.chromium.org/developers/design-documents/network-stack/socks-proxy/

**Comment by shigma** [comment]
那确实可以从 http.config 里读取。我来改吧
