### ISSUE TITLE
bug: 调用 ctx.puppeteer.render 时无法加载本地资源

### ISSUE THREAD

**Issue by TTsdzb** [koishijs/koishi-plugin-puppeteer#25]
插件在渲染 html 内置组件时，如果使用诸如 `file:///home/ubuntu/imgs/1.png` 这样的本地资源，可以正常加载。但如果在调用 `ctx.puppeteer.render` 时使用本地资源，则会无法加载。

Puppeteers 打开标签时默认的 URL 为 `about:blank`，此时 Chrome 无法加载本地资源（`Not allowed to load local resource`）。但渲染内置组件之前，插件会先做以下操作：
```ts
await page.goto('file:///' + resolve(__dirname, '../index.html'))
```
这样标签页的 URL 变成了本地页面，因此之后可以正常加载本地资源了。但是，`ctx.puppeteer.render` 在渲染前并不会做类似的操作，所以页面并不能正常显示。

能否在 `ctx.puppeteer.render` 中也加上这个操作？如果不行，这么做会导致什么其他的问题吗？

**Comment by shigma** [comment]
感觉也是可以的。我之后看看要不要改一下。

**Comment by shigma** [comment]
是不是这个问题呢？

https://github.com/koishijs/koishi-plugin-puppeteer/pull/31/files

**Comment by TTsdzb** [comment]
> 是不是这个问题呢？

并不是，我是在 Debian 上遇到问题的。我的问题只是 Chrome 内部的安全限制，即 `about:blank` 页面就是空的，不应加载任何资源。这个 PR 说的是插件会尝试加载自己的 `index.html` 但无法加载，然而我想说的是 `ctx.puppeteer.render` 根本不会去做这个操作。而且我看不出加上这个操作是否有什么坏处。

可以看一下上面的提及，那里有原始问题。

**Comment by shigma** [comment]
应该已修复，请更新到 3.8.2 版本测试。
