### ISSUE TITLE
Docs: clarify not to use chrome installed by snap on Linux

### ISSUE THREAD

**Issue by MaikoTan** [koishijs/koishi-plugin-puppeteer#29]
The `chrome` browser that we are using can be installed by the `snap`, which is popular in these years and is the default package manager on Ubuntu Desktop. But the namespace mechanisms limits many allowances that causes the failure invoking from the `puppeteer` plugin of Koishi.

Therefore, we should clarify the disadvantages of using `snap` to install the `chrome` with the `puppeteer` plugin and suggest some alternatives methods.

**Comment by Lipraty** [comment]
Updated in #31
